### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1023]
I'm just capturing this, in case it proves difficult to reproduce.

I'm running pepys-admin in a GitHub code-space - which absolutely isn't a target environment for analysts.

The app is responsive, but if I leave it for _some period of time_ (like 30 seconds), it becomes unresponsive.

Pressing `(2) Status` eventually times out with this:
```
(pepys-admin) 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'AdminShell' object has no attribute 'do_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DatabaseError: SSL SYSCALL error: Connection timed out


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspaces/pepys-import/pepys_admin/cli.py", line 120, in <module>
    main()
  File "/workspaces/pepys-import/pepys_admin/cli.py", line 47, in main
    run_shell(db=args.db, path=args.path, training=args.training, viewer=args.viewer)
  File "/workspaces/pepys-import/pepys_admin/cli.py", line 106, in run_shell
    AdminShell(data_store, path).cmdloop()
  File "/usr/local/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/workspaces/pepys-import/pepys_admin/base_cli.py", line 19, in default
    self.aliases[cmd_]()
  File "/workspaces/pepys-import/pepys_admin/admin_cli.py", line 147, in do_status
    if is_schema_created(self.data_store.engine, self.data_store.db_type):
  File "/workspaces/pepys-import/pepys_import/utils/data_store_utils.py", line 195, in is_schema_created
    table_names = inspector.get_table_names(schema="pepys")
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
    return self.dialect.get_table_names(
  File "<string>", line 2, in get_table_names
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3493, in get_table_names
    result = connection.execute(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 280, in execute
    return self._execute_20(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/vscode/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (psycopg2.DatabaseError) SSL SYSCALL error: Connection timed out

[SQL: SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p')]
[parameters: {'schema': 'pepys'}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```
It _looks like_ we lose our database connection.  Will try to reproduce on MS-Windows.

**Comment by robintw** [comment]
This is intriguing.

I've just tried it on my MacBook, loaded Pepys Admin, ran Status, waited 5 minutes, ran Status again, and it all worked fine.

**Comment by IanMayo** [comment]
This doesn't happen on a Windows VM. Putting it down to idiosyncrasy of CodeSpaces.
