### ISSUE TITLE
Error when running pepys_import.bat on a single file

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#106]
I thought that `pepys_import.bat` should work on a single file, as well as a folder (is this correct?).

At the moment it is giving a slightly strange error, below. It seems like the session isn't being opened properly?

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\pepys-deploy\pepys-import\pepys_import\import.py", line 34, in <module>
    main(path=args.path, db=args.db)
  File "C:\pepys-deploy\pepys-import\pepys_import\import.py", line 21, in main
    processor.process(path, data_store, True)
  File "C:\pepys-deploy\pepys-import\pepys_import\file\file_processor.py", line 32, in process
    processed_ctr = self.process_file(path, path, data_store, processed_ctr)
  File "C:\pepys-deploy\pepys-import\pepys_import\file\file_processor.py", line 127, in process_file
    datafile = data_store.get_datafile(filename, file_extension)
  File "C:\pepys-deploy\pepys-import\pepys_import\core\store\data_store.py", line 619, in get_datafile
    self.add_to_datafile_types(datafile_type)
  File "C:\pepys-deploy\pepys-import\pepys_import\core\store\data_store.py", line 939, in add_to_datafile_types
    datafile_types = self.search_datafile_type(datafile_type)
  File "C:\pepys-deploy\pepys-import\pepys_import\core\store\data_store.py", line 515, in search_datafile_type
    self.session.query(self.db_classes.DatafileType)
AttributeError: 'NoneType' object has no attribute 'query'
```

**Comment by IanMayo** [comment]
@robintw - are you on `develop`?

**Comment by robintw** [comment]
Thanks Ian - my fault, I thought I'd pulled from develop but hadn't. Sorted now.

**Comment by IanMayo** [comment]
Re-opening, the import fails for me when I run it from the command line in the root folder:
```
python -m pepys_import.import --path tests/sample_data/track_files/rep_data/rep_test1.rep
```

I get this error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ian/git/pepys-import/pepys_import/import.py", line 34, in <module>
    main(path=args.path, db=args.db)
  File "/Users/ian/git/pepys-import/pepys_import/import.py", line 21, in main
    processor.process(path, data_store, True)
  File "/Users/ian/git/pepys-import/pepys_import/file/file_processor.py", line 32, in process
    processed_ctr = self.process_file(path, path, data_store, processed_ctr)
  File "/Users/ian/git/pepys-import/pepys_import/file/file_processor.py", line 111, in process_file
    first_line = self.get_first_line(full_path)
  File "/Users/ian/git/pepys-import/pepys_import/file/file_processor.py", line 155, in get_first_line
    with open(file_path, "r", encoding="windows-1252") as f:
NotADirectoryError: [Errno 20] Not a directory: 'tests/sample_data/track_files/rep_data/rep_test1.rep/tests/sample_data/track_files/rep_data/rep_test1.rep'
```

It appears the code is trying to construct the path by using the filename twice.

**Comment by robintw** [comment]
Interesting - glad you noticed that Ian!

Just to add a bit to this to help @BarisSari work this out: this works fine when you give it a full path to an individual file (`C:\pepys-import\tests\blah...`) as that's how I tested it (with the Send To menu, which gives full paths).

**Comment by IanMayo** [comment]
Note: this new code fixed it for me:
![image](https://user-images.githubusercontent.com/1108513/75438042-2cf89b00-594f-11ea-9d76-436cba148a77.png)

**Comment by BarisSari** [comment]
It's strange that it was working for me. Anyway, I applied @IanMayo's fix and I'm going to open PR for a hotfix.
