### ISSUE TITLE
Errors when loading incomplete .ini file

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#303]
I created a `bare-bones` Pepys ini-file:
```
[database]
db_name = c:/sample_data/other_formats/pepys.sqlite
db_type = sqlite
```

But, Pepys-admin fell over when trying to read it:
```
C:\git\pepys-dev\pepys-import-develop\bin>CALL set_paths.bat
Successfully set paths for pepys-import
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\configparser.py", line 788, in get
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 916, in __getitem__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 908, in __missing__
KeyError: 'db_username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\git\pepys-dev\pepys-import-develop\pepys_admin\cli.py", line 3, in <module>
    from config import DB_HOST, DB_NAME, DB_PASSWORD, DB_PORT, DB_TYPE, DB_USERNAME
  File "C:\git\pepys-dev\pepys-import-develop\config.py", line 21, in <module>
    DB_USERNAME = config.get("database", "db_username")
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\configparser.py", line 791, in get
configparser.NoOptionError: No option 'db_username' in section: 'database'
Press any key to continue . . .
```

Pepys shouldn't fall over in these circumstances.  Maybe it doesn't need detailed, low-level handlers that allow for missing fields.  We _could_ have a higher level handler that just indicates it had trouble loading the ini file.  I don't feel strongly either way.

**Comment by BarisSari** [comment]
I think ConfigParser's `fallback` option solves this problem but we deleted them recently. We can check the options of that section (`db_username`, `db_password`, etc.) and throw an error if anything is missing. Actually, this might be problematic as well. Because we don't need `db_username` or `db_password` for in-memory SQLite. So, it will fail out of no reason.

**Comment by BarisSari** [comment]
After a few trials, I have come up with this solution:
```python
options = ["db_username", "db_password", "db_host", "db_port", "db_name", "db_type"]
config_options = config.options(section="database")
if not set(options) == set(config_options):  # compare two lists, raise error if not identical
    raise ValueError(
        "At least one of the options is missing in 'database' section! Please check your config file."
    )
```

Do you think it's an acceptable solution, @IanMayo ?

**Comment by IanMayo** [comment]
No, @BarisSari - I'm hoping for something more flexible. 

An analyst using a SQLite database file may delete the fields other than `db_name` and `db_type` - that's just what I did :-D

I think using blank fields as defaults would be a satisfactory solution.  That would prevent the parser from falling over when the PostGres-specific fields were missing.
