### ISSUE TITLE
Various alembic commands fail

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#368]
When running `alembic history` I get the following error:

```
Traceback (most recent call last):
  File "/Users/robin/anaconda3/envs/pepys/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/config.py", line 551, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/command.py", line 430, in history
    _display_history(config, script, base, head)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/command.py", line 399, in _display_history
    base=base or "base", head=head or "heads"
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/base.py", line 215, in walk_revisions
    head, base, inclusive=True, assert_relative_length=False
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/revision.py", line 765, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/revision.py", line 321, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/revision.py", line 501, in _resolve_revision_number
    self._revision_map
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/util/langhelpers.py", line 230, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/revision.py", line 123, in _revision_map
    for revision in self._generator():
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/base.py", line 103, in _load_revisions
    for file_ in Script._list_py_dir(self, vers):
  File "/Users/robin/anaconda3/envs/pepys/lib/python3.7/site-packages/alembic/script/base.py", line 876, in _list_py_dir
    return os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/robin/Documents/IanMayo/pepys-import/migrations/versions'
```

I get the same error when running `alembic show head`.

I assume it is due to Alembic not expecting the `postgres_versions` and `sqlite_versions` folders - but I expect @BarisSari can advise.

**Comment by BarisSari** [comment]
I'll try to produce the same error, @robintw . I'll let you know while I'm working on it.
