### ISSUE TITLE
View `alembic_version` throwing error

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#454]
When I run `pepys-admin > View Table > alembic version`, it throws the below error.

Viewing another table (users) works fine.

```
(pepys-admin) (view) 1
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'AdminShell' object has no attribute 'do_6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'ViewDataShell' object has no attribute 'do_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ian/git/pepys-import/pepys_admin/cli.py", line 49, in <module>
    main()
  File "/Users/ian/git/pepys-import/pepys_admin/cli.py", line 40, in main
    run_admin_shell(data_store, args.path)
  File "/Users/ian/git/pepys-import/pepys_admin/cli.py", line 45, in run_admin_shell
    AdminShell(data_store, path).cmdloop()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/Users/ian/git/pepys-import/pepys_admin/admin_cli.py", line 116, in default
    self.aliases[command_]()
  File "/Users/ian/git/pepys-import/pepys_admin/admin_cli.py", line 105, in do_view_data
    shell.cmdloop()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/Users/ian/git/pepys-import/pepys_admin/view_data_cli.py", line 146, in default
    self.aliases[cmd_]()
  File "/Users/ian/git/pepys-import/pepys_admin/view_data_cli.py", line 78, in do_view_table
    table_cls = getattr(self.data_store.db_classes, table)
AttributeError: module 'pepys_import.core.store.postgres_db' has no attribute 'alembic_version'
```

**Comment by IanMayo** [comment]
Ok.  The above issue is because we don't have SQLAlchemy description for the alembic table.

Running this command should help:
`SELECT * FROM pepys.alembic_version;`

So steps for client are:
* Type `Pepys Admin` into Windows command bar
* Type `6` for `View data`
* Type `2` for `Run SQL`
* Enter this string: `SELECT * FROM pepys.alembic_version;`
* Press `ESC` then `Enter`
* Report last 3 digits of ID number provided.
