### ISSUE TITLE
REP export capability

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#55]
In release 1 we aim to have the ability to export data from the database to REP format.

Release 1 will just export entries in the `States`, `Contacts` and `Comments` tables.  

We will have a Python class/method with this API:
```
export(states, contacts, comments)
```

The method will return the contents of those element lists as a string.  Note: many fields in the classes won't have a representation in REP format, so are ignored.

Note: when looping through the contents of the tables, the platform name to use will be retrieved via the `Sensor` entry in each row.  

It's _probably_ worth cacheing the platform names that are retrieved from sensor ids, since the same platform is likely to appear many times.

The following types of element will be created:
* States - these will be exported as Track Data items: https://debrief.github.io/tutorial/reference.html#replay_track_format
* Comments - these will be exported as `;Narrative:` entries: https://debrief.github.io/tutorial/reference.html#replay_core_annotations
* Contacts - these will be exported as `;Sensor:` elements: https://debrief.github.io/tutorial/reference.html#replay_core_annotations

**Comment by IanMayo** [comment]
The export process is failing.

I populated a PG database using this command: `python\python.exe -m pepys_import.import --path tests\sample_data\track_files`

I then tried to export some data, using `python\python pepys_admin\admin_cli.py`

But, I got this error: 
```
Exported Datafile is: uk_track.
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 214, in onecmd
AttributeError: 'AdminShell' object has no attribute 'do_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function st_asewkb(pepys.geometry) does not exist
LINE 1: ...s."States".sensor_id AS "pepys_States_sensor_id", ST_AsEWKB(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pepys_admin\admin_cli.py", line 206, in <module>
    AdminShell(datastore, args.path).cmdloop()
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 138, in cmdloop
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 216, in onecmd
  File "pepys_admin\admin_cli.py", line 181, in default
    self.aliases[cmd](arg)
  File "pepys_admin\admin_cli.py", line 145, in do_export
    self.datastore.export_datafile(selected_datafile_id)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\pepys_import\core\store\data_store.py", line 1040, in export_datafile
    .filter(self.db_classes.State.source_id == datafile_id)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3186, in all
    return list(self)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\orm\query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\git\pepys_build\pepys-import\20200304_pepys-import\python\Lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function st_asewkb(pepys.geometry) does not exist
LINE 1: ...s."States".sensor_id AS "pepys_States_sensor_id", ST_AsEWKB(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT pepys."States".state_id AS "pepys_States_state_id", pepys."States".time AS "pepys_States_time", pepys."States".sensor_id AS "pepys_States_sensor_id", ST_AsEWKB(pepys."States".location) AS "pepys_States_location", pepys."States".elevation AS "pepys_States_elevation", pepys."States".heading AS "pepys_States_heading", pepys."States".course AS "pepys_States_course", pepys."States".speed AS "pepys_States_speed", pepys."States".source_id AS "pepys_States_source_id", pepys."States".privacy_id AS "pepys_States_privacy_id", pepys."States".created_date AS "pepys_States_created_date"
FROM pepys."States"
WHERE pepys."States".source_id = %(source_id_1)s]
[parameters: {'source_id_1': UUID('f51f7a7f-1b66-4a1b-bc5e-c6ca65e7da90')}]
(Background on this error at: http://sqlalche.me/e/f405)

C:\git\pepys_build\pepys-import\20200304_pepys-import>
```

**Comment by SheikhG1900** [comment]
@IanMayo will you run the following scripts, instead of running admin-cli. If you get the same error, means it is not related to this issue.
```
datastore = DataStore(
        db_username="postgres",
        db_password="postgres",
        db_host="localhost",
        db_port=5432,
        db_name="pepys2",
        welcome_text="Pepys_Admin",
    )
    with datastore.session_scope():
        measurement_summary = datastore.get_status(report_measurement=True)
```

**Comment by SheikhG1900** [comment]
@IanMayo will you run the following scripts, instead of running admin-cli. If you get the same error, means it is not related to this issue.

```
datastore = DataStore(
        db_username="postgres",
        db_password="postgres",
        db_host="localhost",
        db_port=5432,
        db_name="pepys2",
        welcome_text="Pepys_Admin",
    )
    with datastore.session_scope():
        measurement_summary = datastore.get_status(report_measurement=True)
```

**Comment by tahirs95** [comment]
@IanMayo will you run the following scripts, instead of running admin-cli. If you get the same error, means it is not related to this issue.

```
datastore = DataStore(
        db_username="postgres",
        db_password="postgres",
        db_host="localhost",
        db_port=5432,
        db_name="pepys2",
        welcome_text="Pepys_Admin",
    )
    with datastore.session_scope():
        measurement_summary = datastore.get_status(report_measurement=True)
```
